name: Release Packages
on:
  push:
    branches:
      - master
jobs:
  init:
    name: Initialize
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.changes.outputs.matrix}}
      version: ${{steps.version.outputs.date}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Date Version
        id: version
        run: echo "date=$(date +'%Y.%-m.%-d.%-H%M')" >> $GITHUB_OUTPUT
      - name: Directories with Changes
        id: changes
        run: |
          git diff --name-only HEAD~ \
            | awk -F/ '{print $1}' \
            | uniq \
            > directories.txt
          m=''
          while IFS= read -r dir
          do
            if [[ "$dir" == ".github" ]]; then continue; fi
            if [[ "$dir" == ".gitignore" ]]; then continue; fi
            if [[ "$dir" == "README.md" ]]; then continue; fi
            echo "$dir"
            if [[ -z $m ]]; then m="\"$dir\""; else m="$m, \"$dir\""; fi
          done < directories.txt
          echo "matrix=[$m]" >> $GITHUB_OUTPUT
  package:
    needs: [init]
    runs-on: ubuntu-latest
    if: ${{needs.init.outputs.matrix != '[]' && needs.init.outputs.matrix != ''}}
    strategy:
      matrix:
        pkg: ${{fromJson(needs.init.outputs.matrix)}}
    name: Package ${{matrix.pkg}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          source-url: https://nuget.pkg.github.com/nextep-inc/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build Project
        working-directory: ${{matrix.pkg}}
        run: |
          dotnet build \
            --configuration Release \
            /p:Version=${{needs.init.outputs.version}}
      - name: Package Project
        working-directory: ${{matrix.pkg}}
        run: |
          dotnet pack \
            --configuration Release \
            --no-build \
            /p:Version=${{needs.init.outputs.version}}
      - name: Publish Package
        working-directory: ${{matrix.pkg}}
        run: |
          dotnet nuget push \
            "bin/Release/${{matrix.pkg}}.${{needs.init.outputs.version}}.nupkg" \
            --api-key ${{secrets.GITHUB_TOKEN}}
