name: Release Package
on:
  push:
    branches:
      - master
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          source-url: https://nuget.pkg.github.com/nextep-inc/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Set Version
        id: version
        run: echo "date=$(date +'%Y.%-m.%-d.%-H%M')" >> $GITHUB_OUTPUT
      - name: Build Project
        working-directory: src
        run: |
          dotnet build \
            --configuration Release \
            /p:Version=${{steps.version.outputs.date}}
      - name: Package Project
        working-directory: src
        run: |
          dotnet pack \
            --configuration Release \
            --no-build \
            /p:Version=${{steps.version.outputs.date}}
      - name: Publish Package
        working-directory: src
        run: |
          dotnet nuget push \
            "bin/Release/*.${{steps.version.outputs.date}}.nupkg" \
            --api-key ${{secrets.GITHUB_TOKEN}}